version: '3.8'
services:
  arangodb:
    image: arangodb/arangodb:latest
    environment:
      - ARANGO_ROOT_PASSWORD=password
    ports:
      - "8529:8529"
    volumes:
      - arango-data:/var/lib/arangodb3
    networks:
      - arangodb-network

networks:
  arangodb-network:
    driver: bridge

volumes:
  arango-data:
